controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - AB_Chassis
      - Bicep_AB
      - BW_Bicep
      - Elbow_BW
      - TW_Elbow
  - name: fake_end_eff_controller
    type: $(arg fake_execution_type)
    joints:
      - TW_Elbow
initial:  # Define initial robot poses per group
  - group: arm
    pose: Straight